server:
  port: 9999
  servlet:
    session.timeout: 60000
  undertow:
     io-threads: 16
     worker-threads: 256
     buffer-size: 1024
     buffer-per-region: 1024
     direct-buffers: true
logging:
  level.root: warn
  level.org: info
  level.com: warn
  level.io: warn
  level.app: info
swagger:
 enabled: true
